psake/PowerShellBuild

PowerShellBuild/Public/Build-PSBuildModule.ps1

Using the `-filter *.ps1` parameter actually pulls in `*.ps1*` files in Windows PowerShell (note that this is NOT the case with PowerShell Core). A discussion around the idiosyncrasies of the parameter is [here](https://stackoverflow.com/questions/12913734/powershell-get-childitem-filter-operates-differently-to-where-clause-with-same)
I removed the `-Filter` parameter and instead add the filter onto the path. This works in both Windows PowerShell and PowerShell Core.
https://github.com/psake/PowerShellBuild/issues/13
This fixes the issue where you have `*.ps1xml` files in your source folder / subfolder. It ensure that only `*.ps1` script files are included in the module.
I ran a normal build script which had a *.ps1xml file in the source folder and it was not included in the script …

Remove filter parameter and add filter to path

---

PowerShellBuild/Public/Initialize-PSBuild.ps1
PowerShellBuild/psakeFile.ps1

Explicitly set the `BHBuildOutput` variable.
#18 
This allows the environment variable to be used outside of Invoke-Build (I am using it inside Pester tests for example).
This has only been tested in an Invoke-Build environment. But the tasks that have been amended are obviously for psake anyway,

(GH-18) Explicitly set the BHBuildOutput variable

---

PowerShellBuild/PowerShellBuild.psm1

The source folder is called 'Path' but the module script uses 'path'. The case matters on Linux.
The change simply changes the path to the correct case - Windows won't care what the case is but Linux does.
Related issue: #22
Allows the module to be imported under Core on Linux.
The path case was changed and the module imported as normal.

Change path case for use under Core on Linux

---

PowerShellBuild/Public/Test-PSBuildPester.ps1

Fixes the issue found in #31 where the PassThru parameter was replaced by the output file parameters, causing builds to not fail when an output file is specified for use in CI pipelines.
#31 
Ran through a few builds that both used an output file and no output file and behaviour was as it should be.

Add Pester output file parameters rather than replace existing parameters - Fixes #31

---

PowerShellBuild/Public/Build-PSBuildModule.ps1
PowerShellBuild/psakeFile.ps1
README.md

Allows header and footers for the PSM1 file.
Allows a header and footer to be added to:
* The PSM1 script module itself
* Before and after each added script to the compiled PSM1 file
Add's four new configuration variables to allow this:
* $PSBPreference.Build.CompileHeader
* $PSBPreference.Build.CompileFooter
* $PSBPreference.Build.CompileScriptHeader
* $PSBPreference.Build.CompileScriptFooter
#15 and #25 
Allows you to add more code to the PSM1 file than just the compield scripts.
I've tested this in my own project by adding text to the configuration variables and watching the output.

Add PSM1 Module and Script Header / Footer

---

Build/Convert-PSAke.ps1

This pull request resolves the issue where the Build task shows empty dependencies, because the nature of processing was resolving the variable as empty
Fixes #16

Preserve Dependency Variables (Fixes psake#16)

---

PowerShellBuild/IB.tasks.ps1
psakeFile.ps1
tests/IBTasks.tests.ps1

The psake to InvokeBuild conversion is problematic so a standalone InvokeBuild tasks script has been added.
* Added a standalone IB.tasks.ps1 InvokeBuild tasks script;
* Disabled the psake -> InvokeBuild tasks conversion in the build;
* Amended the InvokeBuild Pester test description;
#16 
The psake conversion is problematic. It was agreed in #16 that the InvokeBuild tasks should be standalone _for the time being_.
The InvokeBuild tasks used are the ones created by the conversion script in the last version - with a couple of fixes to the `Assert` statement in the Publish task (which did not work in InvokeBuild) and also to fix the `Build` task to allow it to use `$PSBPreference.Build.Dependencies` which didn;t work for InvokeBuild.

Add standalone InvokeBuild tasks

---

README.md

This fixes the default values that were incorectly set in #28 
* Compile Header / Footer default values are now correctly set to `<empty>`

Fix default values for Compile Header / Footer in documentation

---

CHANGELOG.md
PowerShellBuild/PowerShellBuild.psd1
PowerShellBuild/Public/Test-PSBuildPester.ps1
PowerShellBuild/build.properties.ps1
PowerShellBuild/psakeFile.ps1
README.md

This PR adds the property `ImportModule` to the `test` build property hash. This property is passed to `Test-PSBuildPester` so that Pester can optionally import the module from the specified OutDir. This _feature_ can be optionally used by specifying `$PSBPreference.Test.ImportModule = $true`. 
#45 
Optionally import module prior to running Pesters tests.
1. Simplify `.tests.ps1` files removing redundant code to import the project module.
2. Ensure the module imported for testing is the one build in the `OurDir`.
1. Built module locally. Took contents of output directory and placed them in my module path under `PowerShellBuild/0.5.0` directory. 
2. Created vanilla module via the Plaster Stucco template `v0.2.0`
3. Modified `psakeFile.ps1` file to use `task Test -FromModule PowerShellBuild …

Optionally import module prior to running Pester tests

---

PowerShellBuild/Public/Build-PSBuildModule.ps1
README.md

* If `Build.CompileModule` is `$true` then `Build.Exclude` is treated as an array of regular expressions and the files found to be included into the compiled PSM1 file are matched and excluded;
* Updated the documentation to say that `Build.Exclude` is an array of regular expressions if `Build.CompileModule` is `$true`;
#40 - note that I added this PR for discussion so it's clearer what I'm doing.
Currently, if you compile the module then all PS1 files found recursively from `General.SrcRootDir` are included into the compiled PSM1 file. This is clearly not desired behaviour.
This issue was found, fixed and tested in one of my own private projects. It now has the desired behaviour.
Fixes #40

Fix exclude files on compile

---

PowerShellBuild/PowerShellBuild.psm1

Set-BuildEnvironment runs as part of initialization, and is extraneous here. Causes additional warnings for users who may import the module outside of the intended folder, and increases load time for the module unnecessarily.

Remove Set-BuildEnvironment from psm1

---

PowerShellBuild/IB.tasks.ps1

Invoke-Build Task Fixes
Fix: StageFiles and Pester brought in line with PSake equivalents
Fix: Prereqs as If conditionals
Fix: Dependencies variable doesn't work because Invoke-Build tasks compile dependencies ahead of time. Throw an error instead with proper override guidance

Invoke-Build Task Improvements

---

PowerShellBuild/Public/Test-PSBuildPester.ps1

Before Pester V5, the -PassThru parameter was used.
We could either use the -PassThru parameter, or set the run configuration in the Configuration Parameter.
Currently, the Pester task never really fails, because Invoke-Pester doesn't PassThru
#51 
Before the migration to PesterV5, the PassThru parameter was used, and the replacement in V5 was set to false in the PSBuild Task
Changing it in my machine makes the task fail as it should.

Changes $configuration.Run.PassThru to $True

---

PowerShellBuild/Public/Build-PSBuildUpdatableHelp.ps1

The Module parameter removes the dependency on the $ModuleName variable in the parent scope while maintaining the existing behavior of inheriting its value.
The LandingPagePath key in $cabParams now uses the [IO.Path]::Combine([string[]]) method rather than manual string concatenation
https://github.com/psake/PowerShellBuild/issues/54
This will make it easier to use Build-PSBuildUpdatableHelp in custom psake files or other contexts
All 195 existing Pester tests passed
Also tested in a vacuum as demonstrated by the example in the Issue

Added Module parameter and an [IO.Path]::Combine() to Build-PSBuildUpdatableHelp

---

PowerShellBuild/psakeFile.ps1

See [Related Issue](https://github.com/psake/PowerShellBuild/issues/61)
All existing pester tests pass on the fix branch - I have not found any tests that would have picked this issue up explicitly. 
Also tested on a local install of the module - successfully.
- [] I have added tests to cover my changes.

Addressing Issue #61 - update CodeCoverage Output File Format to fix error

---

PowerShellBuild/Public/Initialize-PSBuild.ps1

The `Initialize-PSBuild` function was not compatible with .NET Framework / PowerShell 5.1 due to the use of the `System.IO.Path.IsPathFullyQualified()` method, introduced with the fix for #27. I changed the function to check if the value of OutDir already started with BHProjectPath rather than testing if OutDir was a fully qualified path on its own.
This seems to have solved the issue and tests are passing. Also, changing the value of `$PSBPreference.Build.OutDir` seems to result in the same behavior before and after the change introduced in this PR, though I don't think any tests were introduced to specifically test the original fix so I'm not 100% certain this is the best solution.
Issue #53 
I still regularly work with PowerShell 5.1 due to legacy .NET Framework dependencies that I'm …

Substitute use of IsPathFullyQualified to restore Windows PowerShell compatibility

---

.markdownlint.json
CHANGELOG.md
PowerShellBuild/PowerShellBuild.psd1

- Bump Pester to latest 5.6.1
- [**#52**](https://github.com/psake/PowerShellBuild/pull/52) Pester object  wasn't being passed back after running tests, causing the Pester task to never fail (via [@webtroter](https://github.com/webtroter))
- [**#55**](https://github.com/psake/PowerShellBuild/pull/55) Add `-Module`  parameter to `Build-PSBuildUpdatableHelp` (via  [@IMJLA](https://github.com/IMJLA))
- [**#60**](https://github.com/psake/PowerShellBuild/pull/60) Fix Windows PowerShell compatibility in `Initialize-PSBuild` (via  [@joshooaj](https://github.com/joshooaj))
- [**#62**](https://github.com/psake/PowerShellBuild/pull/62) Fix code coverage output fle format not working (via  [@OpsM0nkey](https://github.com/OpsM0nkey))

Prepare for 0.6.2 relase

---

CHANGELOG.md
PowerShellBuild/Public/Build-PSBuildModule.ps1

We attempt to append UTF-8 encodings later, but the initial file isn't set to that. This should fix it.
When building a compiled module it was observed that the the Meta tests to check for UTF-8 was filing on the newly created psm1. This fix sets the intial file to be utf-8 encoded.
```
Running tests from 'Meta.tests.ps1'
WARNING: File 
D:\actions-runner\_work\InternalModule\InternalModule\Output\InternalModule\0.7.0\InternalModule.psm1 contains 0x00 bytes. It probably uses Unicode/UTF-16 and needs to be converted to UTF-8. Use Fixer 
"Get-UnicodeFilesList $pwd | ConvertTo-UTF8".
Error: [-] Meta.tests.ps1 failed with:
Message
Expected 0, but got 1.
at $unicodeFilesCount | Should -Be 0, D:\actions-runner\_work\InternalModule\InternalModule\tests\Meta.tests.ps1:24
at <ScriptBlock>, …
```

Build-PSBuildModule Compile UTF-8 File

---

.vscode/settings.json
CHANGELOG.md
PowerShellBuild/build.properties.ps1
PowerShellBuild/psakeFile.ps1
README.md
build.ps1
cspell.json
requirements.psd1
tests/TestModule/.build.ps1
tests/build.tests.ps1

* Refactored build tasks to use `$PSBPreference.TaskDependencies`.
* Introduced `cspell.json` for spell checking configuration.
* Updated `CHANGELOG.md` to reflect changes in task dependencies.
* Adjusted formatting in several scripts for consistency.
Resolves #12 
Verified that existing tests continue to pass.

Loosen Dependencies

---

CHANGELOG.md
PowerShellBuild/PowerShellBuild.psd1

* Updated `ModuleVersion` to `0.7.0` in `PowerShellBuild.psd1`.
* Changed changelog header to reflect the new version.
* Removed duplicate entry in changelog for clarity.

Release: 0.7.0

---

.github/workflows/test.yml

The GitHub action `actions/checkout@v1` is around 6 years old now. This PR bumps us to `actions/checkout@v4`.

Update actions/checkout to v4
